### PR TITLE
Handle 429 errors

### PR DESCRIPTION
**Pull request by desecho**

### CODE REVIEW

**Comment by 3lixy** [comment]
Would it not be better to have a limit ? I normally use a limit of 3 with retry with re-doing http requests.

**Comment by desecho** [comment]
@3lixy Yes you have a good point. It definetely should have a limit. 
Do you have a repository on GitHub which would show the way you're using it? 
For me, it would be more convinient if a library would handle this for me.

**Comment by 3lixy** [comment]
I was thinking about this today and there is probably already a pip module that you can use that will do what you want. A wrapper if you will.
Also you are looking to implement 1 of out at least 75 potential codes, some of which there is not much point in retrying (404 for example).
I have yet to look around for such a module, if I do find one I will post it here.

**Comment by celiao** [comment]
I agree with @3lixy.  I would prefer to keep `tmdbsimple` true to its name, and keep it simple.  

You might want to search `stackoverflow` for approaches to handling HTTP errors in Python.

Closing.

**Pull request closed without merging**
