### PR TITLE
Added language support

### PR DESCRIPTION
**Pull request by desecho**

### CODE REVIEW

**Comment by akofman** [comment]
Bump ! Is this PR going to be merge ? That will be awesome :)

**Comment by celiao** [comment]
Thanks, @akofman.  I'm traveling out of the country for work right now.  I'm hoping to address the outstanding issues and pull requests this weekend after I return.

**Comment by akofman** [comment]
Thanks for your response :+1:

**Comment by akofman** [comment]
Sorry I actually didn't see that it was possible to give the language as an argument for most of the services.
Actually you should keep the actual solution and not merge this PR cause this one could break some services like `movies.images` which doesn't work anymore when the language is specified.

cheers

**Comment by celiao** [comment]
Closing per @akofman's comment.

**Pull request closed without merging**
