### PR TITLE
Add option to pass requests.Session() in stead of using requests()

### PR DESCRIPTION
**Pull request by p0psicles**

### CODE REVIEW

**Comment by p0psicles** [comment]
Continuation from #17

**Comment by p0psicles** [comment]
@celiao could you take a look at this? Should be a fairly small change.

**Comment by p0psicles** [comment]
@celiao please?

**Comment by urwrstkn8mare** [comment]
Yes this would be great!

**Comment by celiao** [comment]
Done!  Sorry for the delay.  :)

**Pull request merged**
