### PR TITLE
Added request timeout setting

### PR DESCRIPTION
**Pull request by hamza-jutt**
Recently I've faced this issue twice where processes get stuck indefinitely until service is restarted. Both times the culprit was not having a timeout.

Also `requests` recommends adding a timeout in every request. More details can be found [here](https://requests.readthedocs.io/en/master/user/quickstart/#timeouts).

### CODE REVIEW

**Comment by blakev** [comment]
This is sorely needed.

**Comment by celiao** [comment]
Sorry for the delay.  I will look at this next weekend, when I am home!

**Comment by celiao** [comment]
Thanks, @hamza-jutt!  Check out how I changed your code to be more clean, consistent, and maintainable.

**Comment by blakev** [comment]
Will you push a pypi update?

**Comment by celiao** [comment]
Done!  https://pypi.org/project/tmdbsimple/

**Pull request merged**
